<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Coldrun.Modules.TruckManagement\TruckManagement.Api\Coldrun.Modules.TruckManagement.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApiRoot\" />
  </ItemGroup>

</Project>
